name: Build, test and lint
on: push

permissions:
  checks: write
  contents: write

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.3.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.3.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Test code
        run: npm test

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
          auto_fix: true
