name: Test PR
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  test-pr:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 16.3.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.3.0
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build code
        run: npm run build
      
      - name: Test code
        run: npm test
        
      - name: Merge DependaBot PR
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}